sudo: false
language: node_js
node_js:
  - "lts/*"
script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Tests
      script: npm run test
    - stage: Produce Coverage
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
